# Combined config testing all features together
config_name: full_feature_test
model_name: gpt2

# Decoder with custom sampling
decoder:
  preset: standard
  temperature: 0.75
  repetition_penalty: 1.05

# Dynamic batching with sorting
batching:
  strategy: sorted_dynamic
  batch_size: 4

# Poisson traffic simulation
traffic_simulation:
  enabled: true
  mode: poisson
  target_qps: 2.0
  seed: 123

max_new_tokens: 64
random_seed: 42
