# Test decoder config presets and custom sampling parameters
config_name: decoder_preset_tests
model_name: gpt2

decoder:
  # Uncomment one preset at a time to test, or use custom params below
  # preset: deterministic   # temp=0, do_sample=false
  # preset: standard        # temp=0.7, top_p=0.9
  # preset: creative        # temp=1.0, top_p=0.95
  # preset: factual         # temp=0.3, top_p=0.85

  # Custom sampling parameters (override preset if both specified)
  temperature: 0.8
  top_p: 0.92
  top_k: 50
  min_p: 0.05
  repetition_penalty: 1.1
  no_repeat_ngram_size: 3
  do_sample: true

max_new_tokens: 64
batch_size: 2
