# Test creative preset with override
config_name: decoder_creative_override
model_name: gpt2

decoder:
  preset: creative
  temperature: 1.2  # Override preset's default

max_new_tokens: 128
batch_size: 1
