# Test constant traffic simulation (fixed inter-arrival times)
config_name: traffic_constant
model_name: gpt2

traffic_simulation:
  enabled: true
  mode: constant
  target_qps: 10.0  # Exactly 100ms between requests

batching:
  strategy: static
  batch_size: 1

max_new_tokens: 64
