# Test Poisson traffic simulation (realistic request arrivals)
config_name: traffic_poisson
model_name: gpt2

traffic_simulation:
  enabled: true
  mode: poisson
  target_qps: 5.0  # 5 queries per second average
  seed: 42         # For reproducibility

batching:
  strategy: static
  batch_size: 1  # Single requests for traffic sim

max_new_tokens: 64
