"""First-run .env file generation for Docker."""

from __future__ import annotations

import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)


def ensure_env_file(project_root: Path | None = None) -> Path:
    """Ensure .env file exists with Docker user mapping (PUID/PGID).

    Creates .env on first run with current user's UID/GID for correct
    file ownership in Docker. Never overwrites existing .env.

    Args:
        project_root: Project root directory. If None, infers by walking up
            from cwd looking for pyproject.toml or .git, falls back to cwd.

    Returns:
        Path to .env file (existing or newly created).
    """
    # Infer project root if not provided
    if project_root is None:
        current = Path.cwd()
        for parent in [current, *current.parents]:
            if (parent / "pyproject.toml").exists() or (parent / ".git").is_dir():
                project_root = parent
                break
        else:
            # Fallback to cwd
            project_root = current

    env_file = project_root / ".env"

    # If .env exists, ensure it has PUID/PGID (append if missing)
    if env_file.exists():
        existing = env_file.read_text()
        missing_vars: list[str] = []
        puid = os.getuid()
        pgid = os.getgid()
        if "PUID=" not in existing:
            missing_vars.append(f"PUID={puid}")
        if "PGID=" not in existing:
            missing_vars.append(f"PGID={pgid}")
        if missing_vars:
            append = "\n# Docker user mapping (auto-appended by llenergymeasure)\n"
            append += "\n".join(missing_vars) + "\n"
            with open(env_file, "a") as f:
                f.write(append)
            logger.info("Appended %s to existing .env", ", ".join(missing_vars))
        return env_file

    # Generate new .env with PUID/PGID
    puid = os.getuid()
    pgid = os.getgid()

    content = f"""# Auto-generated by llenergymeasure
# Docker user mapping for correct file ownership
PUID={puid}
PGID={pgid}
"""

    env_file.write_text(content)
    logger.info("Generated .env with PUID=%d PGID=%d for Docker", puid, pgid)

    return env_file
