"""Render a study YAML file from the generated per-engine config models.

Backs ``llem study init``. The emitted file is a complete, explicit study
specification: what you read is what runs. All assistance happens here, at
authoring time - the tuning fields, their valid ranges, and their defaults are
read straight off the generated Pydantic config models (the same models
``ExperimentConfig`` validates against), so the scaffold never drifts from what
the engine actually accepts.

Two modes:

- bare (``defaults=False``): the tuning fields are present but commented out,
  each annotated with its type, range, and default. Only ``model`` and
  ``engine`` are uncommented, so the file is immediately runnable and the user
  opts into fields by uncommenting them.
- defaults (``defaults=True``): the same fields are uncommented and pinned to
  their model defaults - a reproducible baseline study.

The only difference between the two modes is the comment prefix on the field
lines, so an uncommented bare field lands on exactly the value the defaults
mode would emit.
"""

from __future__ import annotations

import json
import re
from collections.abc import Sequence
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from llenergymeasure.config.introspection import get_engine_config_model
from llenergymeasure.config.ssot import Engine

__all__ = ["all_engine_names", "render_study_scaffold"]

# Sub-sections of every engine's generated Config, in emission order.
_SUB_SECTIONS = ("engine_params", "sampling_params")

# YAML plain-scalar safe set: emit bare, else double-quote via json.dumps.
_PLAIN_SCALAR = re.compile(r"^[A-Za-z0-9_./-]+$")
_YAML_RESERVED = frozenset({"true", "false", "null", "yes", "no", "on", "off", "~"})


def all_engine_names() -> list[str]:
    """Return every engine name in declaration order (transformers, vllm, tensorrt)."""
    return [e.value for e in Engine]


def render_study_scaffold(
    model: str,
    engines: Sequence[str],
    *,
    defaults: bool,
) -> str:
    """Return the study YAML text for a model across one or more engines.

    Args:
        model: HuggingFace model id or local path.
        engines: Engine names to scaffold, in emission order. One entry produces
            a single-engine study; several produce one study with an experiment
            per engine.
        defaults: False emits commented tuning fields (structure only); True
            emits them uncommented at their model defaults (runnable baseline).

    Returns:
        Deterministic YAML text (stable field order, no timestamps), ending in a
        newline. Identical arguments always produce byte-identical output.
    """
    lines: list[str] = []
    lines.extend(_header(engines, defaults=defaults))
    lines.append("")
    lines.append(f"study_name: {_yaml_scalar(_study_name(model, engines))}")
    lines.append("")
    lines.append("# One experiment per engine. task.model is repeated in each so every")
    lines.append("# experiment is a complete, self-contained specification.")
    lines.append("experiments:")
    for engine in engines:
        lines.extend(_experiment_block(engine, model, defaults=defaults))
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Block rendering
# ---------------------------------------------------------------------------


def _header(engines: Sequence[str], *, defaults: bool) -> list[str]:
    """Return the leading comment block explaining the file and how to run it."""
    scope = engines[0] if len(engines) == 1 else "all engines"
    lines = [
        f"# llem study file - {scope}",
        "#",
        "# Generated by `llem study init`. This file is the complete, explicit",
        "# specification of a study: what you read here is exactly what runs.",
        "# Edit it freely, then run:",
        "#",
        "#     llem run <this-file>",
        "#",
    ]
    if defaults:
        lines += [
            "# Every tuning field below is set to its default value, giving a",
            "# reproducible baseline study. Change any value to explore its effect.",
        ]
    else:
        lines += [
            "# The tuning fields below are commented out. Uncomment a line to",
            "# include that field; each line shows its type, valid range, and",
            "# default. Fields left commented use the engine's own default.",
        ]
    return lines


def _experiment_block(engine: str, model: str, *, defaults: bool) -> list[str]:
    """Return one ``experiments:`` list entry for a single engine."""
    lines = [
        f"  - engine: {engine}",
        "    task:",
        f"      model: {_yaml_scalar(model)}",
        f"    {engine}:",
    ]
    sub_models = _sub_models(engine)
    for sub_name in _SUB_SECTIONS:
        sub_model = sub_models.get(sub_name)
        if sub_model is None:
            continue
        lines.append(f"      {sub_name}:")
        for field_name, field_info in sub_model.model_fields.items():
            lines.append(_field_line(field_name, field_info, defaults=defaults))
    return lines


def _field_line(field_name: str, field_info: FieldInfo, *, defaults: bool) -> str:
    """Render one field line: ``<name>: <default>  # <type> <bounds>, default <v>``.

    In bare mode the field is commented out; in defaults mode it is live. Both
    carry the same value and annotation, so uncommenting a bare line yields the
    defaults-mode line verbatim.
    """
    value = _yaml_scalar(field_info.default)
    prefix = "        " if defaults else "        # "
    return f"{prefix}{field_name}: {value}  # {_annotation(field_info)}"


# ---------------------------------------------------------------------------
# Annotation rendering (type + bounds + default, from the typed model only)
# ---------------------------------------------------------------------------


def _annotation(field_info: FieldInfo) -> str:
    """Return ``<type> <bounds>, default <v>`` derived from the field alone."""
    inner = _unwrap_optional(field_info.annotation)
    bounds = _bounds(field_info)
    type_str = _type_str(inner)
    prefix = f"{type_str} {bounds}" if bounds else type_str
    return f"{prefix}, default {_yaml_scalar(field_info.default)}"


def _type_str(inner: Any) -> str:
    """Human-readable type label for an unwrapped annotation."""
    if get_origin(inner) is Literal:
        members = ", ".join(_yaml_scalar(m) for m in get_args(inner))
        return f"one of [{members}]"
    if inner is Any:
        return "any"
    if isinstance(inner, type) and issubclass(inner, BaseModel):
        return "object"
    if inner is bool:
        return "bool"
    if inner is int:
        return "int"
    if inner is float:
        return "float"
    if inner is str:
        return "str"
    return "value"


def _bounds(field_info: FieldInfo) -> str:
    """Return a bounds string like ``>0.0 <=1.0`` from ge/gt/le/lt metadata."""
    parts: list[str] = []
    for op, attr in ((">", "gt"), (">=", "ge"), ("<", "lt"), ("<=", "le")):
        for constraint in field_info.metadata:
            value = getattr(constraint, attr, None)
            if value is not None:
                parts.append(f"{op}{value}")
    return " ".join(parts)


def _unwrap_optional(annotation: Any) -> Any:
    """Strip a ``| None`` wrapper, returning the inner type (or the annotation)."""
    args = get_args(annotation)
    if args and type(None) in args:
        inner = [a for a in args if a is not type(None)]
        if inner:
            return inner[0]
    return annotation


# ---------------------------------------------------------------------------
# Model introspection + scalar rendering
# ---------------------------------------------------------------------------


def _sub_models(engine: str) -> dict[str, type[BaseModel]]:
    """Return an engine's ``engine_params`` / ``sampling_params`` sub-model classes."""
    config = get_engine_config_model(engine)
    out: dict[str, type[BaseModel]] = {}
    for sub_name in _SUB_SECTIONS:
        field = config.model_fields.get(sub_name)
        if field is None:
            continue
        for candidate in get_args(field.annotation) or (field.annotation,):
            if isinstance(candidate, type) and issubclass(candidate, BaseModel):
                out[sub_name] = candidate
                break
    return out


def _yaml_scalar(value: Any) -> str:
    """Render a Python value as a YAML scalar (bool before int; quote unsafe strings)."""
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        if value and _PLAIN_SCALAR.match(value) and value.lower() not in _YAML_RESERVED:
            return value
        return json.dumps(value)
    if isinstance(value, list):
        return "[" + ", ".join(_yaml_scalar(item) for item in value) + "]"
    return repr(value)


def _study_name(model: str, engines: Sequence[str]) -> str:
    """Deterministic study name: model tail slug, plus engine when single-engine."""
    tail = model.split("/")[-1].lower()
    slug = re.sub(r"[^a-z0-9._-]+", "-", tail).strip("-") or "study"
    if len(engines) == 1:
        return f"{slug}-{engines[0]}"
    return slug
