#!/usr/bin/env python3
"""Absorb: the one command a maintainer runs per engine-version bump.

Drives the knowledge-refresh loop for ONE engine's validation rules: cold read
(analyst proposes candidates) -> pool union (analyst + observed collisions +
manual seeds, deduped) -> recall interrogation (ask "is this still present?" for
each shipped rule the fresh pool did not rediscover) -> verification ladder
(citation check on the host, then construction / identity probes in the engine
container; the engine is the arbiter) -> promotion (regenerate the shipped rules
corpus from confirmed candidates and survivors) -> review delta (old-vs-new diff).

Terms a reader needs up front: a "pool" is a version-scoped working file of
candidate rules the stages read and write (never shipped); "residue" is the
shipped rules the probe could not exercise this run; a "sign-off" is the
maintainer marking a residue rule keep-shipping by hand (in absorb_signoff.yaml).

Maintainer tooling, not part of the llem CLI. The only src/ file it writes is the
shipped rules corpus, via the promotion path. Every stage is skippable so a
re-run resumes rather than redoes; pools go only through
:mod:`scripts._candidate_pool`; the corpus is regenerated byte-stably.

The ladder probes the SHIPPED rules directly alongside the pool, because the
analyst can only express a cross-field relation as a ``present`` spec the
construction probe cannot confirm; re-probing each shipped rule's precise spec
re-confirms survivors. Survival is decided on verdict STATUS, never the probe
exit code (0 even when every verdict is infra_error). The probe verdict ALONE
decides disposition: an interrogation ABSENT is only an annotation (a retirement
proposal for the maintainer), never a drop - a rule leaves only via sign-off.

Run: python scripts/absorb.py --engine vllm --source-root SRC/ [--dry-run]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Any, Literal

import yaml

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from engine_versions import _outputs  # noqa: E402
from scripts._candidate_pool import (  # noqa: E402
    SCHEMA_VERSION,
    pool_path,
    slug,
    unverified_verdict,
    write_pool,
)
from scripts._engine_constructors import leaf_of  # noqa: E402
from scripts.analyst_cold_read import Generator, ollama_generator, resolve_version  # noqa: E402
from scripts.check_citations import check_candidate, load_candidates  # noqa: E402

logger = logging.getLogger("absorb")

REPO_ROOT = _PROJECT_ROOT
CORPUS_ROOT = REPO_ROOT / "src" / "llenergymeasure" / "engines"
CONFIRMED = "confirmed"
UNVERIFIED = "unverified"

_UNION_FILE = "union.yaml"
_LADDER_FILE = "ladder.yaml"
_SIGNOFF_FILE = "absorb_signoff.yaml"
_REPORT_FILE = "absorb_review.txt"

_CORPUS_HEADER = (
    "# Shipped engine validation rules. Single runtime source per engine.\n"
    "# Schema + loader: src/llenergymeasure/config/engine_rules/loader.py\n"
    "# severity is closed {error, dormant}; provenance is metadata only.\n"
)
_UNION_HEADER = (
    "# Absorb union pool: analyst cold read + observed collisions + manual seeds,\n"
    "# deduped on candidate id and translated to canonical field paths.\n"
    "# UNVERIFIED candidates for the verification ladder; not a shipped corpus.\n"
)

# provenance.source values the shipped corpus loader accepts (closed enum).
_SOURCE_MAP = {
    "analyst_cold_read": "analyst",
    "recall_interrogation": "analyst",
    "observed_collision": "deterministic_miner",
    "manual": "manual",
    "manual_seed": "manual",
}


# --- Small shared helpers ---


def _status(entry: dict[str, Any]) -> str:
    """Verdict status of a candidate/rule, defaulting to unverified."""
    verdict = entry.get("verdict")
    return (verdict or {}).get("status", UNVERIFIED) if isinstance(verdict, dict) else UNVERIFIED


def _match_fields(entry: dict[str, Any]) -> dict[str, Any]:
    match = entry.get("match")
    return match.get("fields", {}) if isinstance(match, dict) else {}


def _leaf_key(entry: dict[str, Any]) -> tuple[str, tuple[str, ...]]:
    """Coarse identity: severity + sorted match-field leaves (the brief's key)."""
    leaves = tuple(sorted(leaf_of(f) for f in _match_fields(entry)))
    return str(entry.get("severity")), leaves


def _digest(text: str) -> str:
    return hashlib.sha1(text.encode()).hexdigest()[:8]


def _load_yaml_list(path: Path, key: str) -> list[dict[str, Any]]:
    if not path.is_file():
        return []
    document = yaml.safe_load(path.read_text()) or {}
    entries = document.get(key) if isinstance(document, dict) else None
    return [e for e in entries if isinstance(e, dict)] if isinstance(entries, list) else []


def _require_under_repo(path: Path) -> Path:
    """Path relative to the repo root; the probe container only sees /repo."""
    try:
        return path.resolve().relative_to(REPO_ROOT)
    except ValueError as exc:
        raise SystemExit(
            f"--pool-root must live under the repo so the probe container can see it: {path}"
        ) from exc


def _write_pool(
    path: Path, source: str, engine: str, version: str, when: str, cands: list[dict[str, Any]]
) -> None:
    """Write a version-scoped pool file (all absorb pools share one header)."""
    write_pool(
        path,
        source=source,
        engine=engine,
        version=version,
        generated_at=when,
        candidates=cands,
        header=_UNION_HEADER,
    )


# --- Canonical field addressing ---


def canonical_map(engine: str) -> dict[str, str]:
    """Leaf -> ``engine.section.leaf`` from the engine's discovered schema.

    The analyst emits bare leaves; the probe and the shipped loader both need the
    canonical path. ``sampling_params`` wins a leaf shared with ``engine_params``
    (only ``seed`` collides for vllm, and the shipped rule uses sampling_params).
    """
    schema = CORPUS_ROOT / engine / "schema.discovered.json"
    if not schema.is_file():
        return {}
    data = json.loads(schema.read_text())
    mapping: dict[str, str] = {}
    for section in ("sampling_params", "engine_params"):
        for leaf in data.get(section, {}) or {}:
            mapping.setdefault(leaf, f"{engine}.{section}.{leaf}")
    return mapping


def _canonicalise(entry: dict[str, Any], mapping: dict[str, str]) -> None:
    """Rewrite an entry's match-field keys to canonical paths in place."""
    fields = _match_fields(entry)
    entry["match"]["fields"] = {
        mapping.get(leaf_of(path), path): spec for path, spec in fields.items()
    }


# --- Stage 3: pool union ---


def union_candidates(sources: list[list[dict[str, Any]]]) -> list[dict[str, Any]]:
    """Dedup candidates across sources on id, preferring a verdict-carrying entry.

    The id digests the canonical claim, so id equality is claim equality. On
    overlap the entry already carrying a verdict wins (version-scoped memory),
    else first-seen wins. Sorted by id for byte-stable pools.
    """
    by_id: dict[str, dict[str, Any]] = {}
    for candidates in sources:
        for candidate in candidates:
            cid = str(candidate.get("id"))
            existing = by_id.get(cid)
            if existing is None or (
                _status(existing) == UNVERIFIED and _status(candidate) != UNVERIFIED
            ):
                by_id[cid] = candidate
    return [by_id[cid] for cid in sorted(by_id)]


def build_union(pool_dir: Path, engine: str) -> list[dict[str, Any]]:
    """Read the analyst and manual-seed pools, dedup, and canonicalise field paths."""
    sources = [
        _load_yaml_list(pool_dir / "analyst_cold_read.yaml", "candidates"),
        _load_yaml_list(pool_dir / "manual_seeds.yaml", "candidates"),
    ]
    union = union_candidates(sources)
    mapping = canonical_map(engine)
    for candidate in union:
        _canonicalise(candidate, mapping)
    return union


# --- Stage 4: recall interrogation ---

INTERROGATION_PROMPT = """You are verifying whether ONE configuration constraint is STILL enforced in {engine} {version}.

Constraint under review:
  fields:   {fields}
  requires: {predicate}
  severity: {severity}

Decide from the source below whether {engine} still enforces this exact constraint.
Reply with STRICT JSON only, no prose: {{"present": true, "citation": "FILE.py:LINE"}}
Set "present": true ONLY if the guard is actually in the source; cite the file:line where it appears.
Set "present": false when the constraint is absent (ABSENT). Never invent a citation.

SOURCE ({label}):
{source}
"""


def interrogation_prompt(
    engine: str, version: str, rule: dict[str, Any], source: str, label: str
) -> str:
    leaves = ", ".join(sorted(leaf_of(f) for f in _match_fields(rule)))
    predicate = rule.get("message_template") or json.dumps(_match_fields(rule), sort_keys=True)
    return INTERROGATION_PROMPT.format(
        engine=engine,
        version=version,
        fields=leaves or "(none)",
        predicate=predicate,
        severity=rule.get("severity"),
        label=label,
        source=source,
    )


Interrogation = Literal["present", "absent", "unknown"]
"""Three-way recall-interrogation outcome: a parse failure is UNKNOWN, never a
false ABSENT that would mis-flag a real shipped rule for retirement (see
:func:`parse_interrogation` for how each outcome is decided)."""


def parse_interrogation(text: str) -> tuple[Interrogation, str | None]:
    """Parse the interrogation reply into (outcome, citation).

    ``present``  - the reply is a JSON object with ``"present": true``.
    ``absent``   - the reply is a JSON object with ``"present": false`` (the ONLY
      outcome that raises a retirement proposal).
    ``unknown``  - unparseable text, non-dict JSON, or a dict missing ``present``.
      Neither minted nor flagged: the safe default. A garbage LLM reply lands
      here, so it can never masquerade as ABSENT.
    """
    try:
        obj = json.loads(text)
    except json.JSONDecodeError:
        return "unknown", None
    if not isinstance(obj, dict) or "present" not in obj:
        return "unknown", None
    citation = obj.get("citation")
    cite = str(citation) if citation else None
    return ("present" if bool(obj["present"]) else "absent"), cite


def _rule_source(source_root: Path | None, rule: dict[str, Any]) -> tuple[str, str] | None:
    """Line-numbered source of the file this rule was last cited in.

    The old citation is used only to RETRIEVE a file to read, never injected into
    the prompt as a location prior. Returns (numbered_source, label), or None when
    the source cannot be located (no source root, no citation, or no matching file).
    """
    citation = (rule.get("provenance") or {}).get("citation") or ""
    file_part = citation.split(":", 1)[0]
    name = file_part.rsplit("/", 1)[-1]
    if not source_root or not name:
        return None
    hits = sorted(source_root.rglob(name))
    if not hits:
        return None
    # Same basename can live in several packages (scheduler.py, parallel.py both
    # recur in vllm). Prefer the hit whose relative path ends with the cited path
    # on segment boundaries; fall back to the sorted-first basename hit only when
    # no suffix matches, so a bare-basename citation behaves exactly as before.
    cited_parts = file_part.split("/")

    def _suffix(hit: Path) -> bool:
        rel = hit.relative_to(source_root).as_posix().split("/")
        return rel[-len(cited_parts) :] == cited_parts

    chosen = next((h for h in hits if _suffix(h)), hits[0])
    lines = chosen.read_text().splitlines()
    numbered = "\n".join(f"{i:6d}  {line}" for i, line in enumerate(lines, start=1))
    return numbered, chosen.relative_to(source_root).as_posix()


def interrogate_rule(
    engine: str,
    version: str,
    rule: dict[str, Any],
    source_root: Path | None,
    generate: Generator,
    run_date: str,
) -> tuple[Interrogation, dict[str, Any] | None]:
    """Ask whether a shipped rule is still present; on a PRESENT reply mint a candidate.

    Returns (outcome, candidate). A rule whose source cannot be located is NOT
    sent to the model (outcome UNKNOWN by construction; interrogating with no
    evidence draws a guaranteed false ABSENT), so nothing is minted or proposed.
    A PRESENT reply mints a candidate carrying the OLD rule's precise predicate
    (source ``recall_interrogation``) so the ladder can confirm it; an ABSENT
    reply raises a retirement proposal (annotation only; the probe verdict still
    decides disposition); an UNKNOWN reply mints and proposes nothing.
    """
    located = _rule_source(source_root, rule)
    if located is None:
        return "unknown", None  # no retrievable source: judging from the text alone is worthless
    source, label = located
    reply = generate(interrogation_prompt(engine, version, rule, source, label), 0.0)
    outcome, citation = parse_interrogation(reply.text)
    if outcome != "present":
        return outcome, None
    leaves = sorted(leaf_of(f) for f in _match_fields(rule))
    candidate: dict[str, Any] = {
        "id": f"{engine}_recall_{rule['severity']}_{slug('_'.join(leaves))}_{_digest(str(rule['id']))}",
        "engine": engine,
        "engine_version": version,
        "severity": rule["severity"],
        "match": {"fields": dict(_match_fields(rule))},
    }
    if rule["severity"] == "dormant" and rule.get("normalised_fields"):
        candidate["normalised_fields"] = list(rule["normalised_fields"])
    candidate["provenance"] = {
        "source": "recall_interrogation",
        "engine_version": version,
        "date": run_date,
        "from_rule": rule["id"],
        "interrogation_citation": citation,
    }
    candidate["verdict"] = unverified_verdict()
    return "present", candidate


def recall_interrogation(
    engine: str,
    version: str,
    old_rules: list[dict[str, Any]],
    pool_leaf_keys: set[tuple[str, tuple[str, ...]]],
    source_root: Path | None,
    generate: Generator,
    run_date: str,
) -> tuple[list[dict[str, Any]], list[str]]:
    """Interrogate every shipped rule the fresh pool did not rediscover.

    Returns (new candidates, ids of rules reported ABSENT). See
    :func:`interrogate_rule` for the per-rule outcome contract: a rule with no
    retrievable source is skipped, ABSENT ids become retirement proposals (never
    automatic drops), and UNKNOWN mints and proposes nothing.
    """
    minted: list[dict[str, Any]] = []
    absent: list[str] = []
    for rule in old_rules:
        if _leaf_key(rule) in pool_leaf_keys:
            continue  # rediscovered by a fresh candidate; no interrogation needed
        outcome, candidate = interrogate_rule(
            engine, version, rule, source_root, generate, run_date
        )
        if outcome == "present" and candidate is not None:
            minted.append(candidate)
        elif outcome == "absent":
            absent.append(str(rule["id"]))
    return minted, absent


# --- Stage 5: verification ladder ---


def citation_pass_rate(
    union: list[dict[str, Any]], source_root: Path, pool_dir: Path
) -> tuple[int, int]:
    """Tier 1: run the citation checker over the pool (uncited entries skipped)."""
    tmp = pool_dir / "_citation_input.yaml"
    eng = str(union[0].get("engine")) if union else ""
    ver = str(union[0].get("engine_version")) if union else ""
    _write_pool(tmp, "absorb_union", eng, ver, "", union)
    try:
        candidates = [c for c in load_candidates(tmp) if c.citation is not None]
        passed = sum(1 for c in candidates if check_candidate(c, source_root).ok)
        return passed, len(candidates)
    finally:
        tmp.unlink(missing_ok=True)


def run_probe(engine: str, probe_input: Path, run_date: str) -> None:
    """Probe candidates inside the engine container via the shell wrapper.

    A non-zero exit is a hard error: the wrapper crashing before it writes any
    verdict back (docker pull failure, image missing, entrypoint crash) would
    otherwise leave every candidate ``unverified``, promotion would touch
    nothing, and the operator would read a clean "corpus unchanged" as a passing
    probe. Fail loudly naming the wrapper so a bump is never silently a no-op.
    Verdict-level failure (all ``infra_error``) is still caught separately by the
    ladder gate; this catches the case where no verdict was written at all.
    """
    wrapper = "scripts/probe_candidates.sh"
    rel = _require_under_repo(probe_input)
    result = subprocess.run(
        [wrapper, engine, "--candidates", str(rel), "--date", run_date],
        cwd=REPO_ROOT,
        check=False,
    )
    if result.returncode != 0:
        raise SystemExit(
            f"probe failure: {wrapper} {engine} exited {result.returncode} before writing "
            f"verdicts back to {rel}; nothing was probed. Fix the engine image / wrapper and "
            "re-run - absorb will not silently skip the probe."
        )


def probe_ladder(
    engine: str,
    entries: list[dict[str, Any]],
    pool_dir: Path,
    run_date: str,
    *,
    clean_room: bool,
    skip_probe: bool,
) -> dict[str, dict[str, Any]]:
    """Probe union candidates + shipped rules; return id -> verdict.

    Within-version memory: entries already carrying a verdict are not re-probed
    unless ``--clean-room``. Fails loudly when a probe run yields only infra_error
    verdicts (wrong container / engine not importable) - the probe process exits 0
    regardless, so success is gated on the verdicts, not the exit code.
    """
    ladder_path = pool_dir / _LADDER_FILE
    # A prior verdict may live on the entry itself or in the persisted ladder
    # file; the ladder file (freshest probe result) takes precedence.
    verdicts: dict[str, dict[str, Any]] = {}
    for entry in entries:
        own = entry.get("verdict")
        if isinstance(own, dict) and own.get("status", UNVERIFIED) != UNVERIFIED:
            verdicts[str(entry["id"])] = own
    prior = {str(e["id"]): e.get("verdict") for e in _load_yaml_list(ladder_path, "candidates")}
    verdicts.update({k: v for k, v in prior.items() if isinstance(v, dict)})

    to_probe = [
        e
        for e in entries
        if clean_room or verdicts.get(str(e["id"]), {}).get("status", UNVERIFIED) == UNVERIFIED
    ]
    version = str(entries[0].get("engine_version")) if entries else ""
    if to_probe and not skip_probe:
        probe_input = pool_dir / "_probe_input.yaml"
        _write_pool(
            probe_input, "absorb_ladder", engine, version, run_date, [dict(e) for e in to_probe]
        )
        run_probe(engine, probe_input, run_date)
        probed = {
            str(e["id"]): e.get("verdict") for e in _load_yaml_list(probe_input, "candidates")
        }
        statuses = [v.get("status") for v in probed.values() if isinstance(v, dict)]
        if statuses and all(s == "infra_error" for s in statuses):
            raise SystemExit(
                "ladder failure: every probe verdict is infra_error (wrong container or "
                "engine not importable); re-run scripts/probe_candidates.sh in the engine image"
            )
        for cid, verdict in probed.items():
            if isinstance(verdict, dict):
                verdicts[cid] = verdict
        probe_input.unlink()

    # Persist the merged ladder state for the next resume, then writeback.
    for entry in entries:
        entry["verdict"] = verdicts.get(str(entry["id"]), unverified_verdict())
    _write_pool(ladder_path, "absorb_ladder", engine, version, run_date, entries)
    return verdicts


# --- Stage 6: promotion ---


def candidate_to_rule(
    candidate: dict[str, Any], engine: str, version: str, run_date: str
) -> dict[str, Any]:
    """Promote a confirmed candidate to a shipped rule (canonical key order)."""
    provenance = candidate.get("provenance") or {}
    rule: dict[str, Any] = {
        "id": candidate["id"],
        "engine": engine,
        "severity": candidate["severity"],
        "match": {"fields": dict(_match_fields(candidate))},
    }
    message = provenance.get("rationale") or provenance.get("predicate")
    if message:
        rule["message_template"] = message
    if candidate["severity"] == "dormant" and candidate.get("normalised_fields"):
        rule["normalised_fields"] = list(candidate["normalised_fields"])
    out_provenance: dict[str, Any] = {
        "source": _SOURCE_MAP.get(str(provenance.get("source")), "migrated"),
        "verified": "construction",
        "engine_version": version,
    }
    citation = _citation_str(candidate.get("citation"))
    if citation:
        out_provenance["citation"] = citation
    out_provenance["date"] = run_date
    rule["provenance"] = out_provenance
    return rule


def _citation_str(citation: Any) -> str | None:
    if isinstance(citation, dict) and citation.get("file"):
        lines = citation.get("lines") or []
        return f"{citation['file']}:{lines[0]}" if lines else str(citation["file"])
    return None


def _mark_human(rule: dict[str, Any], version: str, run_date: str) -> dict[str, Any]:
    """A signed-off residue rule ships with human provenance."""
    promoted = {k: v for k, v in rule.items() if k != "provenance"}
    promoted["provenance"] = {
        "source": _SOURCE_MAP.get(str((rule.get("provenance") or {}).get("source")), "migrated"),
        "verified": "human",
        "engine_version": version,
        "date": run_date,
    }
    return promoted


class Delta:
    """Mechanical old-vs-new corpus diff, grouped by disposition."""

    def __init__(self) -> None:
        self.survived: list[str] = []
        self.added: list[str] = []
        self.proposed_retirements: list[str] = []  # interrogation ABSENT; annotation only
        self.changed: list[str] = []
        self.residue: list[str] = []
        self.signed: list[str] = []  # residue rules that shipped via sign-off this run


def promote(
    engine: str,
    version: str,
    run_date: str,
    old_rules: list[dict[str, Any]],
    verdicts: dict[str, dict[str, Any]],
    union: list[dict[str, Any]],
    signed_off: set[str],
    interrogation_absent: list[str],
) -> tuple[list[dict[str, Any]], Delta]:
    """Build the new corpus and the review delta from the ladder verdicts.

    The probe verdict ALONE decides disposition (the module docstring says why
    interrogation ABSENT never does). A shipped rule survives when the engine
    confirmed it directly OR a confirmed pool candidate shares its field family. A
    rule the probe could not confirm (unconfirmed / unprobeable) is NOT dropped:
    construction probes have false negatives (constraints enforced past __init__),
    so it becomes residue that ships only once the maintainer signs it off. A rule
    not tested this run (unverified / infra_error / --skip-probe) is kept
    untouched. ABSENT ids are surfaced as retirement proposals (in the delta and
    as sign-off annotations); confirmed candidates on a new field family are added
    with their pool ids.
    """
    delta = Delta()
    delta.proposed_retirements = list(interrogation_absent)
    confirmed_leaf_keys = {_leaf_key(c) for c in union if _status(c) == CONFIRMED}
    old_leaf_keys = {_leaf_key(r) for r in old_rules}
    new_rules: list[dict[str, Any]] = []

    for rule in old_rules:
        rid = str(rule["id"])
        status = verdicts.get(rid, {}).get("status", UNVERIFIED)
        family_confirmed = _leaf_key(rule) in confirmed_leaf_keys
        if status == CONFIRMED or family_confirmed:
            new_rules.append(rule)
            delta.survived.append(rid)
            if status != CONFIRMED:
                delta.changed.append(rid)  # kept via a pool candidate: possible in-place drift
        elif status in ("unconfirmed", "unprobeable"):
            if rid in signed_off:
                new_rules.append(_mark_human(rule, version, run_date))
                delta.survived.append(rid)
                delta.signed.append(rid)  # consumed a sign-off mark; persist it
            else:
                delta.residue.append(rid)
        else:  # unverified / infra_error: not tested this run - keep untouched
            new_rules.append(rule)
            delta.survived.append(rid)

    for candidate in sorted(union, key=lambda c: str(c["id"])):
        if _status(candidate) != CONFIRMED or _leaf_key(candidate) in old_leaf_keys:
            continue
        new_rules.append(candidate_to_rule(candidate, engine, version, run_date))
        delta.added.append(str(candidate["id"]))

    new_rules.sort(key=lambda r: str(r["id"]))
    return new_rules, delta


# --- Residue sign-off + review delta report ---


def read_signoff(signoff_dir: Path) -> set[str]:
    """Rule ids the maintainer marked ``human_confirmed: true`` in the sign-off.

    ``signoff_dir`` is the versioned, git-tracked ``outputs/`` snapshot dir (not
    the gitignored candidates pool): the human approval record is a durable
    decision that must survive a fresh clone.
    """
    entries = _load_yaml_list(signoff_dir / _SIGNOFF_FILE, "residue")
    return {str(e["id"]) for e in entries if e.get("human_confirmed") is True}


def write_signoff(
    signoff_dir: Path, delta: Delta, old_by_id: dict[str, dict[str, Any]], absent: set[str]
) -> None:
    """Write the residue sign-off file, persisting consumed marks.

    Two kinds of entry are written, sorted by id for byte-stable regeneration:
    the current unsigned residue (rules awaiting a human mark), and every rule
    that shipped via the sign-off path this run (``human_confirmed: true``,
    ``delta.signed``). Persisting the consumed marks is what stops the corpus
    oscillating: a signed rule ships via ``delta.survived`` (not residue), so
    without re-emitting its mark the next run would find none, route the rule
    back to residue, and unship it. Prior marks on ids still in residue are
    preserved so a maintainer's edit is not clobbered. Rules the interrogation
    reported ABSENT carry ``interrogation: absent`` (a retirement proposal; see
    the file header the maintainer reads).
    """
    prior = {
        str(e["id"]): bool(e.get("human_confirmed"))
        for e in _load_yaml_list(signoff_dir / _SIGNOFF_FILE, "residue")
    }

    def entry(rid: str, confirmed: bool) -> dict[str, Any]:
        row: dict[str, Any] = {
            "id": rid,
            "severity": old_by_id[rid].get("severity"),
            "fields": sorted(old_by_id[rid].get("match", {}).get("fields", {})),
        }
        if rid in absent:
            row["interrogation"] = "absent"  # retirement proposal; maintainer decides
        row["human_confirmed"] = confirmed
        return row

    rows = [entry(rid, prior.get(rid, False)) for rid in delta.residue]
    rows += [entry(rid, True) for rid in delta.signed]
    rows.sort(key=lambda r: str(r["id"]))
    header = (
        "# Material residue: shipped rules the probe could not exercise this run.\n"
        "# Set human_confirmed: true to keep shipping a rule you have verified by hand;\n"
        "# the next absorb run consumes the mark. Unmarked residue is not shipped\n"
        "# until you mark it (withheld pending sign-off, not retired). An entry with\n"
        "# interrogation: absent is a retirement proposal: decline the mark to let the\n"
        "# rule lapse, or mark it to keep shipping it.\n"
    )
    signoff_dir.mkdir(parents=True, exist_ok=True)
    (signoff_dir / _SIGNOFF_FILE).write_text(
        header + yaml.safe_dump({"residue": rows}, sort_keys=False)
    )


def render_delta(delta: Delta, citations: tuple[int, int]) -> str:
    passed, checked = citations
    lines = [
        "Absorb review delta",
        "===================",
        f"citation check       : {passed}/{checked} cited candidates entailed",
        f"survived             : {len(delta.survived)}",
        f"added                : {len(delta.added)}",
        f"retirement proposals : {len(delta.proposed_retirements)}"
        " (interrogation ABSENT; annotation only, never auto-applied)",
        f"changed              : {len(delta.changed)}"
        " (kept via pool candidate; review for in-place drift)",
        f"residue              : {len(delta.residue)} (awaiting human sign-off)",
    ]
    for label, ids in (
        ("added", delta.added),
        ("retirement proposals", delta.proposed_retirements),
        ("changed", delta.changed),
        ("residue (sign-off)", delta.residue),
    ):
        if ids:
            lines.append(f"\n{label}:")
            lines += [f"  - {rid}" for rid in ids]
    return "\n".join(lines) + "\n"


# --- Orchestration ---


def load_shipped_rules(engine: str) -> tuple[Path, list[dict[str, Any]]]:
    path = CORPUS_ROOT / engine / "rules.yaml"
    document = yaml.safe_load(path.read_text()) if path.is_file() else {}
    rules = document.get("rules") if isinstance(document, dict) else None
    return path, [r for r in rules if isinstance(r, dict)] if isinstance(rules, list) else []


# Line-wrap width the shipped corpora were written with; kept so a re-mine that
# changes nothing reproduces the file byte-for-byte.
_CORPUS_WIDTH = 100


def serialize_corpus(engine: str, version: str, rules: list[dict[str, Any]]) -> str:
    document = {
        "schema_version": SCHEMA_VERSION,
        "engine": engine,
        "engine_version": version,
        "rules": rules,
    }
    body = yaml.safe_dump(document, sort_keys=False, default_flow_style=False, width=_CORPUS_WIDTH)
    return _CORPUS_HEADER + body


def run_cold_read(engine: str, source_root: Path, pool_root: Path, run_date: str) -> None:
    subprocess.run(
        [
            sys.executable,
            "scripts/analyst_cold_read.py",
            "--engine",
            engine,
            "--source-root",
            str(source_root),
            "--pool-root",
            str(pool_root),
            "--date",
            run_date,
        ],
        cwd=REPO_ROOT,
        check=True,
    )


def absorb(args: argparse.Namespace) -> int:
    engine = args.engine
    version = resolve_version(engine)
    run_date = args.date or date.today().isoformat()
    pool_dir = pool_path(args.pool_root, engine, version, _UNION_FILE).parent
    pool_dir.mkdir(parents=True, exist_ok=True)
    # The sign-off is the durable human approval record, so it lives in the
    # versioned, git-tracked outputs/ snapshot dir (sibling of the gitignored
    # candidates/ pool), not in the throwaway pool workspace.
    #
    # Derived relative to pool_root (not via engine_versions._outputs.outputs_dir)
    # on purpose: _outputs hardcodes the real repo root, so routing through it
    # would break test isolation and custom pool roots by writing into the real
    # engine_versions/ tree. With the default pool root this lands exactly in the
    # git-tracked engine_versions/<engine>/v<safe>/outputs/ dir.
    signoff_dir = pool_dir.parent / "outputs"
    logger.info(
        "absorb engine=%s version=%s date=%s dry_run=%s", engine, version, run_date, args.dry_run
    )

    if not args.skip_cold_read:
        if not args.source_root:
            raise SystemExit(
                "--source-root is required for the cold read (or pass --skip-cold-read)"
            )
        run_cold_read(engine, args.source_root, args.pool_root, run_date)

    union = build_union(pool_dir, engine)
    _, old_rules = load_shipped_rules(engine)
    old_by_id = {str(r["id"]): r for r in old_rules}

    interrogation_absent: list[str] = []
    if not args.skip_interrogation:
        pool_leaf_keys = {_leaf_key(c) for c in union}
        generate = ollama_generator(args.ollama_host, args.model)
        minted, interrogation_absent = recall_interrogation(
            engine, version, old_rules, pool_leaf_keys, args.source_root, generate, run_date
        )
        union = union_candidates([union, minted])
        for candidate in minted:
            _canonicalise(candidate, canonical_map(engine))

    _write_pool(pool_dir / _UNION_FILE, "absorb_union", engine, version, run_date, union)

    citations = (
        citation_pass_rate(union, args.source_root, pool_dir) if args.source_root else (0, 0)
    )
    ladder_entries = union + [dict(r) for r in old_rules]
    verdicts = probe_ladder(
        engine,
        ladder_entries,
        pool_dir,
        run_date,
        clean_room=args.clean_room,
        skip_probe=args.skip_probe,
    )
    for candidate in union:  # carry ladder verdicts back onto the pool candidates
        candidate["verdict"] = verdicts.get(str(candidate["id"]), unverified_verdict())

    if all(v.get("status") in (UNVERIFIED, "infra_error") for v in verdicts.values()):
        logger.warning(
            "probe ladder verified nothing this run; every rule kept untouched, corpus unchanged"
        )

    signed_off = read_signoff(signoff_dir)
    new_rules, delta = promote(
        engine, version, run_date, old_rules, verdicts, union, signed_off, interrogation_absent
    )
    write_signoff(signoff_dir, delta, old_by_id, set(interrogation_absent))

    report = render_delta(delta, citations)
    print(report)
    (pool_dir / _REPORT_FILE).write_text(report)

    corpus_path = CORPUS_ROOT / engine / "rules.yaml"
    corpus_bytes = serialize_corpus(engine, version, new_rules)
    if args.dry_run:
        logger.info(
            "dry-run: would write %d rules to %s (not written)", len(new_rules), corpus_path
        )
    else:
        corpus_path.write_text(corpus_bytes)
        logger.info("wrote %d rules to %s", len(new_rules), corpus_path)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Absorb one engine-version bump into the shipped rules corpus."
    )
    parser.add_argument(
        "--engine", required=True, choices=_outputs.ENGINES, help="Engine to absorb."
    )
    parser.add_argument(
        "--source-root", type=Path, help="Pinned engine package dir (citations resolve against it)."
    )
    parser.add_argument(
        "--pool-root",
        type=Path,
        default=REPO_ROOT / "engine_versions",
        help="Root of the version-scoped candidate pool (must be under the repo).",
    )
    parser.add_argument(
        "--date", help="Provenance date (default: today; set for reproducible output)."
    )
    parser.add_argument(
        "--clean-room",
        action="store_true",
        help="Ignore within-version verdict memory; re-probe all.",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Report everything; do not write the shipped corpus."
    )
    parser.add_argument(
        "--skip-cold-read", action="store_true", help="Reuse the existing analyst pool file."
    )
    parser.add_argument(
        "--skip-interrogation", action="store_true", help="Skip the recall-interrogation pass."
    )
    parser.add_argument(
        "--skip-probe", action="store_true", help="Skip the container probes (citation tier only)."
    )
    parser.add_argument("--ollama-host", default="http://localhost:11434")
    parser.add_argument("--model", default="qwen2.5-coder:32b")
    return parser


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    return absorb(build_parser().parse_args(argv))


if __name__ == "__main__":
    raise SystemExit(main())
