#!/usr/bin/env python3
"""Generate the Python API reference markdown from docstrings.

Stdlib-only renderer. Walks ``llenergymeasure.__all__``, extracts
docstrings + signatures + Pydantic field metadata via ``inspect``,
renders a single markdown page at
``docs/reference/api/llenergymeasure.md`` with a pre-1.0 disclaimer
admonition prepended.

Build-time only - the output file is gitignored. Re-runs on every
``make docs-build`` invocation and on every CI build.

Run::

    python scripts/generate_api_docs.py
"""

from __future__ import annotations

import inspect
import sys
from pathlib import Path
from typing import Any

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_PROJECT_ROOT / "src"))
sys.path.insert(0, str(_PROJECT_ROOT))

import llenergymeasure  # noqa: E402
from scripts._docgen_common import write_doc  # noqa: E402

_OUT_PATH = _PROJECT_ROOT / "docs" / "reference" / "api" / "llenergymeasure.md"

_DISCLAIMER = """\
---
title: Python API reference
sidebar_label: API reference
---

> ⚠️ **Pre-1.0 - Python API surface is unstable.**
> LLenergyMeasure is currently pre-1.0. The Python library API
> documented here is **not yet a stable public surface** - class
> signatures, function names, and module paths may change between
> minor versions without notice.
>
> The supported user-facing interfaces are the **CLI**
> (`llem run`, `llem doctor`) and the **YAML study config**. See
> [CLI reference](/reference/cli) and
> [Study config](/reference/study-config) for stable contracts.
>
> The library API will stabilise at v1.0.0.

> Auto-generated by `scripts/generate_api_docs.py` from docstrings in
> `src/llenergymeasure/`. Do not edit manually - edits are overwritten
> on the next build.

"""


def _format_annotation(annotation: Any) -> str:
    """Render a type annotation as a compact string."""
    if annotation is inspect.Signature.empty:
        return ""
    text = str(annotation)
    # Strip noisy module prefixes that pollute the rendered table cells.
    for prefix in ("typing.", "<class '", "<enum '", "'>"):
        text = text.replace(prefix, "")
    return text


def _is_required_default(default: Any) -> bool:
    """Detect 'no default set' sentinels across stdlib + Pydantic."""
    if default is inspect.Parameter.empty or default is ...:
        return True
    # Pydantic v2 uses a singleton PydanticUndefined for required fields.
    return type(default).__name__ == "PydanticUndefinedType"


def _format_default(default: Any) -> str:
    """Render a default value for a markdown table cell."""
    if _is_required_default(default):
        return "_(required)_"
    if default is None:
        return "`None`"
    if isinstance(default, str) and default == "":
        return '`""`'
    return f"`{default!r}`"


def _render_function(name: str, func: Any) -> str:
    """Render a top-level function: name + fenced signature + docstring."""
    sig = inspect.signature(func)
    doc = inspect.getdoc(func) or "_(no docstring)_"
    # Long signatures break heading layout; render the signature as a fenced
    # code block instead so it line-wraps naturally.
    return f"## `{name}`\n\n```python\n{name}{sig}\n```\n\n{doc}\n\n---\n\n"


def _render_pydantic_class(name: str, cls: type) -> str:
    """Render a Pydantic model class: docstring + field table."""
    parts = [f"## `class {name}`\n"]
    doc = inspect.getdoc(cls) or "_(no docstring)_"
    parts.append(doc)
    parts.append("")

    fields = getattr(cls, "model_fields", None)
    if not fields:
        parts.append("---\n")
        return "\n".join(parts)

    parts.append("### Fields\n")
    parts.append("| Field | Type | Default | Description |")
    parts.append("|-------|------|---------|-------------|")
    for field_name, field_info in fields.items():
        type_str = _format_annotation(field_info.annotation)
        default_str = _format_default(field_info.default)
        description = (field_info.description or "").replace("\n", " ").strip()
        # Escape pipes in description (plain-text cell content).
        description = description.replace("|", "\\|")
        parts.append(f"| `{field_name}` | `{type_str}` | {default_str} | {description} |")
    parts.append("")
    parts.append("---\n")
    return "\n".join(parts)


def main() -> int:
    parts: list[str] = [_DISCLAIMER]

    # Render in __all__ order (the project's intentional ordering),
    # but with __version__ pulled to the front as a single-line entry.
    names = list(llenergymeasure.__all__)
    if "__version__" in names:
        names.remove("__version__")
        parts.append(
            f"## `__version__`\n\nCurrent version: `{llenergymeasure.__version__}`\n\n---\n\n"
        )

    for name in names:
        symbol = getattr(llenergymeasure, name)
        if inspect.isfunction(symbol):
            parts.append(_render_function(name, symbol))
        elif inspect.isclass(symbol):
            parts.append(_render_pydantic_class(name, symbol))

    write_doc(_OUT_PATH, "".join(parts))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
