#!/usr/bin/env python3
"""Generate CLI reference documentation from the llem Typer app.

Uses click introspection (via typer.main.get_command) to extract command
and parameter metadata, then renders a structured Markdown reference.

Usage:
    python scripts/generate_cli_reference.py
    python scripts/generate_cli_reference.py --output docs/cli-reference.md

Output:
    Markdown to stdout (or --output path). Suitable for inlining into docs/cli-reference.md.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "src"))


def _option_names(opts: list[str]) -> str:
    """Format option names as a comma-separated string."""
    return ", ".join(f"`{o}`" for o in opts if o.startswith("-"))


def _type_label(param: object) -> str:
    """Return a human-readable type string for a click parameter."""
    import click

    type_obj = getattr(param, "type", None)
    if type_obj is None:
        return ""
    if isinstance(type_obj, click.types.BoolParamType):
        return "flag"
    if isinstance(type_obj, click.types.IntParamType):
        return "int"
    if isinstance(type_obj, click.types.StringParamType):
        return "str"
    if isinstance(type_obj, click.types.Path):
        return "path"
    type_name = getattr(type_obj, "name", str(type_obj))
    return type_name.lower()


def _render_command(name: str, cmd: object) -> list[str]:
    """Render a single command's documentation."""
    import click

    lines: list[str] = []
    help_text = (getattr(cmd, "help", "") or "").strip()

    lines.append(f"### `llem {name}`")
    lines.append("")
    if help_text:
        lines.append(help_text)
        lines.append("")

    params = getattr(cmd, "params", [])

    # Separate positional args from options
    args = [p for p in params if isinstance(p, click.Argument)]
    opts = [p for p in params if isinstance(p, click.Option)]

    # Positional arguments table
    if args:
        lines.append("**Arguments:**")
        lines.append("")
        lines.append("| Argument | Type | Required | Description |")
        lines.append("|----------|------|----------|-------------|")
        for arg in args:
            type_str = _type_label(arg)
            required = "yes" if arg.required else "no"
            desc = (getattr(arg, "help", "") or "").strip()
            lines.append(f"| `{arg.name}` | {type_str} | {required} | {desc} |")
        lines.append("")

    # Options table
    if opts:
        lines.append("**Options:**")
        lines.append("")
        lines.append("| Flag | Short | Type | Default | Description |")
        lines.append("|------|-------|------|---------|-------------|")
        for opt in opts:
            opt_opts: list[str] = getattr(opt, "opts", [])
            long_opts = [o for o in opt_opts if o.startswith("--")]
            short_opts = [o for o in opt_opts if o.startswith("-") and not o.startswith("--")]

            long_str = ", ".join(f"`{o}`" for o in long_opts) if long_opts else ""
            short_str = ", ".join(f"`{o}`" for o in short_opts) if short_opts else ""

            type_str = _type_label(opt)
            default = opt.default
            if default is None:
                default_str = ""
            elif isinstance(default, bool):
                default_str = f"`{str(default).lower()}`"
            else:
                default_str = f"`{default}`"

            desc = (getattr(opt, "help", "") or "").strip()
            lines.append(f"| {long_str} | {short_str} | {type_str} | {default_str} | {desc} |")
        lines.append("")

    return lines


def render_markdown() -> str:
    import typer
    import typer.main

    from llenergymeasure.cli import app

    click_app = typer.main.get_command(app)
    commands = getattr(click_app, "commands", {})

    lines: list[str] = [
        "<!-- Auto-generated by scripts/generate_cli_reference.py -- do not edit manually -->",
        "",
        "## CLI Reference",
        "",
        "llem provides two commands and one flag.",
        "",
        "```",
        "llem run [CONFIG] [OPTIONS]   # run an experiment or study",
        "llem config [OPTIONS]         # show environment and configuration status",
        "llem --version                # print version and exit",
        "```",
        "",
    ]

    # Render commands in a fixed order: run first, then config
    command_order = ["run", "config"]
    for cmd_name in command_order:
        if cmd_name in commands:
            lines.extend(_render_command(cmd_name, commands[cmd_name]))

    # Any remaining commands not in the fixed order
    for cmd_name, cmd in commands.items():
        if cmd_name not in command_order:
            lines.extend(_render_command(cmd_name, cmd))

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate CLI reference Markdown")
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=None,
        help="Write output to this file path (default: stdout)",
    )
    args = parser.parse_args()

    markdown = render_markdown()

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(markdown)
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        print(markdown)


if __name__ == "__main__":
    main()
