#!/usr/bin/env python3
"""Generate curation docs showing discovered vs curated fields per engine.

For each engine, produces a Markdown file with a four-column table showing
every discovered parameter and whether llem's Pydantic layer curates it.

Output: docs/generated/curation-{engine}.md

Run: python scripts/generate_curation_doc.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from llenergymeasure.config.introspection import get_engine_params
from llenergymeasure.config.schema_loader import SchemaLoader
from llenergymeasure.config.ssot import Engine

ENGINES = tuple(e.value for e in Engine)

_ENGINE_DISPLAY_NAMES = {
    "transformers": "Transformers",
    "vllm": "vLLM",
    "tensorrt": "TensorRT-LLM",
}


def _get_curated_names(engine: str) -> set[str]:
    """Get the set of leaf field names curated by llem for this engine."""
    params = get_engine_params(engine)
    return {meta["name"] for meta in params.values()}


def _render_section(
    section_name: str,
    fields: dict[str, dict],
    curated: set[str],
) -> list[str]:
    """Render a table for one section (engine_params or sampling_params)."""
    lines = [
        f"### {section_name}",
        "",
        "| Field | Type | Default | Curated? |",
        "|-------|------|---------|----------|",
    ]
    for name, meta in sorted(fields.items()):
        type_str = meta.get("type", "unknown").replace("|", "\\|")
        default = meta.get("default")
        default_str = f"`{default}`" if default is not None else "`null`"
        is_curated = "yes" if name in curated else "-"
        lines.append(f"| `{name}` | {type_str} | {default_str} | {is_curated} |")
    lines.append("")
    return lines


def generate_engine_doc(engine: str, loader: SchemaLoader | None = None) -> str:
    """Generate curation doc for one engine."""
    if loader is None:
        loader = SchemaLoader()
    schema = loader.load_schema(engine)
    curated = _get_curated_names(engine)

    engine_total = len(schema.engine_params)
    sampling_total = len(schema.sampling_params)
    all_discovered = {**schema.engine_params, **schema.sampling_params}
    curated_count = sum(1 for name in all_discovered if name in curated)
    total = engine_total + sampling_total

    display_name = _ENGINE_DISPLAY_NAMES.get(engine, engine.title())
    lines = [
        f"# {display_name} Parameter Curation",
        "",
        "<!-- Auto-generated by scripts/generate_curation_doc.py -- do not edit manually -->",
        "",
        f"Engine version: **{schema.engine_version}**  ",
        f"Discovered at: {schema.discovered_at}  ",
        f"Discovery method: {schema.discovery_method}",
        "",
        f"**Summary:** {curated_count}/{total} parameters curated "
        f"({engine_total} engine + {sampling_total} sampling discovered)",
        "",
    ]

    if schema.engine_params:
        lines.extend(_render_section("Engine Parameters", schema.engine_params, curated))

    if schema.sampling_params:
        lines.extend(_render_section("Sampling Parameters", schema.sampling_params, curated))

    return "\n".join(lines)


def main() -> None:
    """Generate curation docs for all engines."""
    output_dir = Path(__file__).parent.parent / "docs" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)
    loader = SchemaLoader()

    for engine in ENGINES:
        content = generate_engine_doc(engine, loader)
        output_path = output_dir / f"curation-{engine}.md"
        output_path.write_text(content)
        print(f"Generated: {output_path}")


if __name__ == "__main__":
    main()
