#!/usr/bin/env python3
"""Generate the Python API reference markdown via Sphinx.

Replaces the stdlib renderer in scripts/generate_api_docs.py with a
library-based pipeline:

    sphinx-build -b markdown -c docs/sphinx docs/sphinx <tmp>
    -> autodoc + autodoc_pydantic walk llenergymeasure.__all__
    -> sphinx-markdown-builder converts the doctree to GFM
    -> this script prepends the Docusaurus front matter + pre-1.0
       disclaimer and lands the result at docs/api/llenergymeasure.md

Build-time only -- the output file is gitignored. Re-runs on every
docs site build (CI + Cloudflare Pages).

Run::

    python scripts/generate_api_docs_sphinx.py

Requires the ``[docs]`` extra: ``pip install -e .[docs]``.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# Sphinx renders cross-references to other autodoc'd symbols as
# Markdown links of the form `[ExperimentConfig](#llenergymeasure.ExperimentConfig)`.
# Docusaurus auto-generates anchor IDs from heading slugs (lowercased,
# punctuation-stripped) so the Sphinx-style FQN anchors never resolve,
# producing "Broken anchor" warnings on every build. The target of
# the link is always the same page (single-file output); strip the
# link wrapping and keep only the visible text.
_INTERNAL_XREF_RE = re.compile(r"\[([^\]]+)\]\(#llenergymeasure\.[^\)]+\)")

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
_SPHINX_CONFIG_DIR = _PROJECT_ROOT / "docs" / "sphinx"
_OUT_PATH = _PROJECT_ROOT / "docs" / "api" / "llenergymeasure.md"

# Make llenergymeasure importable for the version-section header (mirrors
# what scripts/generate_api_docs.py does -- needed to pull __version__
# without invoking sphinx-build twice).
sys.path.insert(0, str(_PROJECT_ROOT / "src"))
import llenergymeasure  # noqa: E402

# Front matter + pre-1.0 disclaimer, prepended to the Sphinx output so
# Docusaurus picks up the page title / sidebar label and renders the
# stability admonition above the API surface. Kept ASCII-only to match
# project convention for committed files (this script is committed; the
# output it writes is gitignored, but the disclaimer text lives here).
_FRONT_MATTER = """\
---
title: Python API reference
sidebar_label: API reference
---

> **Pre-1.0 - Python API surface is unstable.**
> LLenergyMeasure is currently pre-1.0. The Python library API
> documented here is **not yet a stable public surface** - class
> signatures, function names, and module paths may change between
> minor versions without notice.
>
> The supported user-facing interfaces are the **CLI**
> (`llem run`, `llem config`) and the **YAML study config**. See
> [CLI reference](/docs/cli-reference) and
> [Study config](/docs/study-config) for stable contracts.
>
> The library API will stabilise at v1.0.0.

> Auto-generated by `scripts/generate_api_docs_sphinx.py` from
> docstrings in `src/llenergymeasure/`. Do not edit manually -
> edits are overwritten on the next build.

"""


def main() -> int:
    _OUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    # sphinx-build needs an output dir and isolates the doctree cache
    # under tempdir so repeat runs are reproducible (no cached state
    # bleeds between builds, matching the stdlib renderer's behaviour).
    with tempfile.TemporaryDirectory(prefix="llem-sphinx-") as tmp:
        out_dir = Path(tmp) / "out"
        doctree_dir = Path(tmp) / "doctrees"
        cmd = [
            sys.executable,
            "-m",
            "sphinx",
            "-b",
            "markdown",
            "-c",
            str(_SPHINX_CONFIG_DIR),
            "-d",
            str(doctree_dir),
            "-q",  # quiet; warnings still surface, info noise suppressed
            str(_SPHINX_CONFIG_DIR),
            str(out_dir),
        ]
        result = subprocess.run(cmd, check=False)
        if result.returncode != 0:
            print(
                f"ERROR: sphinx-build failed (exit {result.returncode}). "
                "Ensure the [docs] extra is installed: pip install -e .[docs]",
                file=sys.stderr,
            )
            return result.returncode

        rendered = out_dir / "index.md"
        if not rendered.exists():
            print(
                f"ERROR: expected Sphinx output at {rendered}, not found. "
                "Check docs/sphinx/conf.py and docs/sphinx/index.rst.",
                file=sys.stderr,
            )
            return 1

        body = rendered.read_text()

    # Strip the Sphinx-generated H1 ("# Python API reference") since
    # Docusaurus derives the page heading from front-matter `title`.
    # Two-line strip handles both "# Title\n\n" and "# Title\n".
    lines = body.splitlines()
    while lines and (lines[0].startswith("# ") or lines[0].strip() == ""):
        # Drop the H1 and any trailing blank line.
        was_heading = lines[0].startswith("# ")
        lines.pop(0)
        if was_heading:
            break

    cleaned = "\n".join(lines).lstrip("\n")
    cleaned = _INTERNAL_XREF_RE.sub(r"`\1`", cleaned)

    # Synthesise a __version__ section: autodoc renders __version__ as the
    # `str` class docstring (not useful), so inject a one-line block at
    # the top of the API surface. Matches the legacy renderer's output.
    version_block = f"### `__version__`\n\nCurrent version: `{llenergymeasure.__version__}`\n\n"

    _OUT_PATH.write_text(_FRONT_MATTER + version_block + cleaned)
    print(f"Generated: {_OUT_PATH}")

    # Mirror the stale-build sentinel the old renderer relied on: any
    # other file the previous run left in docs/api/ is removed so the
    # Docusaurus plugin doesn't pick up phantom pages.
    for sibling in _OUT_PATH.parent.iterdir():
        if sibling.is_file() and sibling.name != _OUT_PATH.name:
            sibling.unlink()
        elif sibling.is_dir():
            shutil.rmtree(sibling)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
