import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

import {ROUTES, GITHUB_REPO, EDIT_URL, SITE_TITLE} from './src/constants';

// Runs in Node.js — no client-side code (no browser APIs, no JSX).
//
// Five+one-plugin IA (Get Started + Diátaxis pillars + Contributing):
//   docs/get-started/  — onboarding: install, quick-start, concepts, audience routing
//   docs/tutorials/    — guided learning (Tutorials sidebar; classic preset slot)
//   docs/how-to/       — goal-driven recipes (How-to sidebar)
//   docs/reference/    — exhaustive lookup: CLI, study config, Python API, engines
//   docs/explanation/  — research + engineering voice: Methodology, Architecture, Why, Ecosystem
//   docs/contributing/ — internals + developer docs (last on purpose)
//
// Content lives in docs/ at the repo root; this Docusaurus instance lives
// in website/ and points its plugins at ../docs/<subdir>. .product/ is
// gitignored project-decision storage and is deliberately not referenced.

const config: Config = {
  title: SITE_TITLE,
  tagline: 'Energy & efficiency measurement for LLM inference',

  future: {
    v4: true,
  },

  // baseUrl defaults to GH Pages subpath (henrycgbaker.github.io/llenergymeasure/);
  // override via DOCUSAURUS_BASE_URL=/ for hosts that serve at root (CF Pages
  // previews + production at *.pages.dev). url is left as the GH Pages origin
  // so canonical URLs always point at the production source of truth, even
  // when rendered on a preview host.
  url: 'https://henrycgbaker.github.io',
  baseUrl: process.env.DOCUSAURUS_BASE_URL ?? '/llenergymeasure/',

  organizationName: 'henrycgbaker',
  projectName: 'llenergymeasure',

  onBrokenLinks: 'throw',

  markdown: {
    // Treat .md files as plain CommonMark (not MDX). Docs in this repo use
    // standard markdown features only — HTML comments, GFM tables, code
    // blocks — and don't need JSX. CommonMark mode is more permissive.
    format: 'md',
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  themes: ['@docusaurus/theme-mermaid'],

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          path: '../docs/tutorials',
          routeBasePath: 'tutorials',
          sidebarPath: './sidebarsTutorials.ts',
          editUrl: EDIT_URL,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'get-started',
        path: '../docs/get-started',
        routeBasePath: 'get-started',
        sidebarPath: './sidebarsGetStarted.ts',
        editUrl: EDIT_URL,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'how-to',
        path: '../docs/how-to',
        routeBasePath: 'how-to',
        sidebarPath: './sidebarsHowTo.ts',
        editUrl: EDIT_URL,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'reference',
        path: '../docs/reference',
        routeBasePath: 'reference',
        sidebarPath: './sidebarsReference.ts',
        // The api/ subtree is auto-generated by scripts/generate_api_docs.py
        // and gitignored. The rest of reference/ is mostly auto-generated too
        // (CLI, engine schemas/curation/invariants); editUrl points to the
        // markdown for hand-edited pages, but generated pages should not be
        // edited via the GitHub UI.
        editUrl: EDIT_URL,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'explanation',
        path: '../docs/explanation',
        routeBasePath: 'explanation',
        sidebarPath: './sidebarsExplanation.ts',
        editUrl: EDIT_URL,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'contributing',
        path: '../docs/contributing',
        routeBasePath: 'contributing',
        sidebarPath: './sidebarsContributing.ts',
        editUrl: EDIT_URL,
      },
    ],
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        language: ['en'],
        docsDir: [
          '../docs/get-started',
          '../docs/tutorials',
          '../docs/how-to',
          '../docs/reference',
          '../docs/explanation',
          '../docs/contributing',
        ],
        docsRouteBasePath: [
          'get-started',
          'tutorials',
          'how-to',
          'reference',
          'explanation',
          'contributing',
        ],
        indexBlog: false,
      },
    ],
  ],

  themeConfig: {
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: SITE_TITLE,
      items: [
        {
          type: 'dropdown',
          label: 'Get Started',
          position: 'left',
          to: ROUTES.getStarted,
          items: [
            {label: 'Install', to: '/get-started/install'},
            {label: 'Quick start', to: '/get-started/quick-start'},
            {label: 'Concepts in 2 minutes', to: '/get-started/concepts-in-2-minutes'},
            {label: 'Choose your path', to: '/get-started/choose-your-path'},
            {label: 'For policy readers', to: '/get-started/for-policy-readers'},
          ],
        },
        {
          type: 'dropdown',
          label: 'Tutorials',
          position: 'left',
          to: ROUTES.tutorials,
          items: [
            {label: 'First measurement', to: '/tutorials/first-measurement'},
            {label: 'Multi-engine study', to: '/tutorials/multi-engine-study'},
          ],
        },
        {
          type: 'dropdown',
          label: 'How-to',
          position: 'left',
          to: ROUTES.howTo,
          items: [
            {label: 'Install', to: '/how-to/install'},
            {label: 'Docker setup', to: '/how-to/docker-setup'},
            {label: 'Run with Docker + vLLM', to: '/how-to/run-with-docker-vllm'},
            {label: 'Run with TensorRT-LLM', to: '/how-to/run-with-tensorrt-llm'},
            {label: 'Interpret results', to: '/how-to/interpret-results'},
            {label: 'Single-GPU or limited hardware', to: '/how-to/single-gpu-or-limited-hardware'},
            {label: 'Troubleshoot', to: '/how-to/troubleshoot'},
            {label: 'FAQ', to: '/how-to/faq'},
          ],
        },
        {
          type: 'dropdown',
          label: 'Reference',
          position: 'left',
          to: ROUTES.reference,
          items: [
            {label: 'CLI', to: '/reference/cli'},
            {label: 'Study config', to: '/reference/study-config'},
            {label: 'Dataset format', to: '/reference/dataset-format'},
            {label: 'Results schema', to: '/reference/results-schema'},
            {label: 'Library API', to: '/reference/library/run_experiment'},
            {label: 'Engines', to: '/reference/engines/configuration'},
          ],
        },
        {
          type: 'dropdown',
          label: 'Explanation',
          position: 'left',
          to: ROUTES.explanation,
          items: [
            {label: 'Overview', to: '/explanation/overview'},
            {label: 'Methodology', to: '/explanation/methodology/methodology'},
            {label: 'Architecture', to: '/explanation/architecture/architecture-overview'},
            {label: 'Why', to: '/explanation/why'},
            {label: 'Ecosystem', to: '/explanation/ecosystem'},
          ],
        },
        {
          type: 'dropdown',
          label: 'Contributing',
          position: 'left',
          to: ROUTES.contributing,
          items: [
            {label: 'Development', to: '/contributing/development'},
            {label: 'Miner pipeline', to: '/contributing/miner-pipeline'},
            {label: 'Extending miners', to: '/contributing/extending-miners'},
            {label: 'Schema refresh', to: '/contributing/schema-refresh'},
            {label: 'Validation invariant corpus', to: '/contributing/validation-invariant-corpus'},
            {label: 'Release process', to: '/contributing/release-process'},
            {label: 'Preview deployments', to: '/contributing/preview-deployments'},
            {label: 'Citation', to: '/contributing/citation'},
            {label: 'Roadmap', to: '/contributing/roadmap'},
          ],
        },
        {href: GITHUB_REPO, label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Get started',
          items: [
            {label: 'Install', to: ROUTES.getStarted},
            {label: 'First measurement', to: ROUTES.tutorials},
            {label: 'CLI reference', to: '/reference/cli'},
          ],
        },
        {
          title: 'Understand',
          items: [
            {label: 'Explanation', to: ROUTES.explanation},
            {label: 'Energy measurement', to: '/explanation/methodology/energy-measurement'},
            {label: 'Architecture overview', to: '/explanation/architecture/architecture-overview'},
          ],
        },
        {
          title: 'More',
          items: [
            {label: 'Contributing', to: ROUTES.contributing},
            {label: 'GitHub', href: GITHUB_REPO},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} ${SITE_TITLE} contributors`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
