import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

import {ROUTES, GITHUB_REPO, EDIT_URL, SITE_TITLE} from './src/constants';

// Runs in Node.js — no client-side code (no browser APIs, no JSX).
//
// Six-plugin IA (Diátaxis with Explanation split into research-vs-engineering):
//   docs/tutorials/    — guided learning (Tutorials sidebar; classic preset slot)
//   docs/how-to/       — goal-driven recipes (How-to sidebar)
//   docs/reference/    — exhaustive lookup: CLI, study config, Python API, engines
//   docs/methodology/  — research voice: what we measure, energy methodology, comparison context
//   docs/architecture/ — engineering voice: dataflow, validation pipeline, miner pipeline (with diagrams)
//   docs/contributing/ — internals + developer docs (last on purpose)
//
// Content lives in docs/ at the repo root; this Docusaurus instance lives
// in website/ and points its plugins at ../docs/<subdir>. .product/ is
// gitignored project-decision storage and is deliberately not referenced.

const config: Config = {
  title: SITE_TITLE,
  tagline: 'Energy & efficiency measurement for LLM inference',

  future: {
    v4: true,
  },

  url: 'https://henrycgbaker.github.io',
  baseUrl: '/llenergymeasure/',

  organizationName: 'henrycgbaker',
  projectName: 'llenergymeasure',

  onBrokenLinks: 'throw',

  markdown: {
    // Treat .md files as plain CommonMark (not MDX). Docs in this repo use
    // standard markdown features only — HTML comments, GFM tables, code
    // blocks — and don't need JSX. CommonMark mode is more permissive.
    format: 'md',
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  themes: ['@docusaurus/theme-mermaid'],

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          path: '../docs/tutorials',
          routeBasePath: 'tutorials',
          sidebarPath: './sidebarsTutorials.ts',
          editUrl: EDIT_URL,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'how-to',
        path: '../docs/how-to',
        routeBasePath: 'how-to',
        sidebarPath: './sidebarsHowTo.ts',
        editUrl: EDIT_URL,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'reference',
        path: '../docs/reference',
        routeBasePath: 'reference',
        sidebarPath: './sidebarsReference.ts',
        // The api/ subtree is auto-generated by scripts/generate_api_docs.py
        // and gitignored. The rest of reference/ is mostly auto-generated too
        // (CLI, engine schemas/curation/invariants); editUrl points to the
        // markdown for hand-edited pages, but generated pages should not be
        // edited via the GitHub UI.
        editUrl: EDIT_URL,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'methodology',
        path: '../docs/methodology',
        routeBasePath: 'methodology',
        sidebarPath: './sidebarsMethodology.ts',
        editUrl: EDIT_URL,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'architecture',
        path: '../docs/architecture',
        routeBasePath: 'architecture',
        sidebarPath: './sidebarsArchitecture.ts',
        editUrl: EDIT_URL,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'contributing',
        path: '../docs/contributing',
        routeBasePath: 'contributing',
        sidebarPath: './sidebarsContributing.ts',
        editUrl: EDIT_URL,
      },
    ],
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        language: ['en'],
        docsDir: [
          '../docs/tutorials',
          '../docs/how-to',
          '../docs/reference',
          '../docs/methodology',
          '../docs/architecture',
          '../docs/contributing',
        ],
        docsRouteBasePath: [
          'tutorials',
          'how-to',
          'reference',
          'methodology',
          'architecture',
          'contributing',
        ],
        indexBlog: false,
      },
    ],
  ],

  themeConfig: {
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: SITE_TITLE,
      items: [
        {to: ROUTES.tutorials, label: 'Tutorials', position: 'left'},
        {to: ROUTES.howTo, label: 'How-to', position: 'left'},
        {to: ROUTES.reference, label: 'Reference', position: 'left'},
        {to: ROUTES.methodology, label: 'Methodology', position: 'left'},
        {to: ROUTES.architecture, label: 'Architecture', position: 'left'},
        {to: ROUTES.contributing, label: 'Contributing', position: 'left'},
        {href: GITHUB_REPO, label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Get started',
          items: [
            {label: 'First measurement', to: ROUTES.tutorials},
            {label: 'Install', to: '/how-to/install'},
            {label: 'CLI reference', to: '/reference/cli'},
          ],
        },
        {
          title: 'Understand',
          items: [
            {label: 'Methodology', to: ROUTES.methodology},
            {label: 'Energy measurement', to: '/methodology/energy-measurement'},
            {label: 'Architecture overview', to: '/architecture/architecture-overview'},
          ],
        },
        {
          title: 'More',
          items: [
            {label: 'Contributing', to: ROUTES.contributing},
            {label: 'GitHub', href: GITHUB_REPO},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} ${SITE_TITLE} contributors`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
