"""``gh`` subprocess helpers for ``llem report-gaps --open-pr``.

Isolated in its own module so the core scanning logic in
:mod:`llenergymeasure.study.report_gaps` stays synchronous and mockable. Tests
monkeypatch :func:`_run_gh` to assert the right arguments would have been
invoked without shelling out.

Design note: we intentionally never pass ``--ready-for-review``. Draft-only is
a fixed commitment in ``runtime-config-validation.md`` §4.9.1 (never-automate
list). The PR body carries full evidence so a maintainer can reviewably flip
it to ready-for-review themselves.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from llenergymeasure.study.report_gaps import RuleCandidate, render_candidates_yaml

logger = logging.getLogger(__name__)


__all__ = [
    "DraftPRRequest",
    "GhNotFoundError",
    "open_draft_pr",
]


class GhNotFoundError(RuntimeError):
    """``gh`` binary missing or not authenticated — caller should fall back to ``--out``."""


@dataclass(frozen=True)
class DraftPRRequest:
    engine: str
    candidates: tuple[RuleCandidate, ...]
    corpus_path: Path
    branch_name: str
    pr_title: str
    pr_body: str


def plan_request(engine: str, candidates: list[RuleCandidate], corpus_root: Path) -> DraftPRRequest:
    """Build a :class:`DraftPRRequest` for the given engine/candidates.

    Branch and title follow ``runtime-config-validation.md`` §4.7 — one PR per
    engine per day, regardless of how many candidates were synthesised. A
    maintainer can still split manually if the evidence warrants it.
    """
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    rule_id = (candidates[0].candidate_id if candidates else "report-gaps") if candidates else ""
    source = candidates[0].source if candidates else "report-gaps"
    return DraftPRRequest(
        engine=engine,
        candidates=tuple(candidates),
        corpus_path=corpus_root / f"{engine}.yaml",
        branch_name=f"feedback/report-gaps-{engine}-{today}",
        pr_title=f"feat(rules): auto-proposed rule from {source} — {rule_id}",
        pr_body=_render_pr_body(engine, candidates),
    )


def _render_pr_body(engine: str, candidates: list[RuleCandidate]) -> str:
    lines: list[str] = []
    lines.append(f"## Auto-proposed rule candidates for `{engine}`\n")
    lines.append(
        "Generated by `llem report-gaps --open-pr`. "
        "Draft PR — waiting for CI (`config-rules-refresh.yml`) to vendor-validate.\n"
    )
    verified = [c for c in candidates if c.verified]
    unverified = [c for c in candidates if not c.verified]
    counts = {"high": 0, "medium": 0, "low": 0}
    for c in candidates:
        counts[c.confidence] = counts.get(c.confidence, 0) + 1
    lines.append(
        f"**Confidence mix:** {counts.get('high', 0)} high / "
        f"{counts.get('medium', 0)} medium / {counts.get('low', 0)} low\n"
    )
    if unverified:
        lines.append(
            f"**⚠ {len(unverified)} UNVERIFIED** candidate(s) from a `dedup_mode=off` study — "
            "review manually, these are not proven canonicaliser gaps.\n"
        )
    for c in candidates:
        lines.append(f"### `{c.candidate_id}` ({c.confidence} confidence, {c.source})")
        lines.append(f"- **Severity:** `{c.severity}`")
        if c.message_template:
            lines.append(f"- **Message template:** `{c.message_template}`")
        if c.evidence:
            lines.append("- **Evidence:**")
            for k, v in c.evidence.items():
                lines.append(f"  - `{k}`: `{v}`")
        lines.append("")
    lines.append("### Proposed YAML")
    lines.append("```yaml")
    lines.append(render_candidates_yaml(verified).rstrip())
    lines.append("```")
    return "\n".join(lines) + "\n"


def open_draft_pr(request: DraftPRRequest, *, runner: Any = None) -> str:
    """Create the branch, append YAML, commit, push, open a draft PR.

    ``runner`` is a hook injected by tests — defaults to :func:`_run_gh`. On
    missing ``gh`` binary or auth failure raises :class:`GhNotFoundError` so
    the CLI can print a suggestion to fall back to ``--out``.
    """
    run = runner or _run_gh
    if run is _run_gh and shutil.which("gh") is None:
        raise GhNotFoundError(
            "The `gh` CLI is not on PATH. Run `gh auth login` or re-run "
            "`llem report-gaps` with `--out proposed.yaml` to dump the YAML locally."
        )

    run(["git", "checkout", "-b", request.branch_name])
    # Append YAML to the corpus — maintainer can inspect the diff in the PR.
    verified = [c for c in request.candidates if c.verified]
    if verified:
        yaml_block = render_candidates_yaml(verified)
        if request.corpus_path.exists():
            existing = request.corpus_path.read_text()
            request.corpus_path.write_text(existing.rstrip() + "\n" + yaml_block)
        else:
            request.corpus_path.parent.mkdir(parents=True, exist_ok=True)
            request.corpus_path.write_text(yaml_block)
        run(["git", "add", str(request.corpus_path)])
        run(
            [
                "git",
                "commit",
                "-m",
                f"feat(rules): auto-proposed rules for {request.engine}",
            ]
        )
        run(["git", "push", "-u", "origin", request.branch_name])

    result = run(
        [
            "gh",
            "pr",
            "create",
            "--draft",
            "--title",
            request.pr_title,
            "--body",
            request.pr_body,
        ]
    )
    return result if isinstance(result, str) else ""


def _run_gh(argv: list[str]) -> str:
    """Execute ``argv`` as a subprocess; return stdout (trimmed)."""
    try:
        completed = subprocess.run(  # intentional invocation of gh/git
            argv,
            check=True,
            text=True,
            capture_output=True,
        )
    except FileNotFoundError as exc:
        raise GhNotFoundError(str(exc)) from exc
    except subprocess.CalledProcessError as exc:
        logger.warning("gh invocation failed: %s (stderr: %s)", argv, exc.stderr)
        raise
    return completed.stdout.strip()
